### ISSUE TITLE
Features: Commands

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-design#124]
# Features concept

This is a part of Features concept. This issue discusses `Command`s. See also #129.
## Commands

`Command`s are classes that allow for manipulations on Tree Model. When executed, a command performs an action on Tree Model. `Command`s should use `Batch` API to manipulate Tree Model.

Each `Feature` should introduce one or more appropriate `Command`s. `Command` may introduce new `Element` or attribute, which will later be recognized and handled by feature's converters.

`Command` will probably extend `Observable`.
### Executing command

`Command` is registered to the editor and can be executed from different parts of code without having a reference to actual `Command` object. Command execution will be available through `editor.exec( 'command_name' )` or similar call on editor instance. If a `Feature` introduces only one command, the command's name should be same as feature's name. If there are more commands, use `Feature:command`, i.e. `editor.exec( 'image:insert' )` (similarly to event naming). `Command` execution is always connected with focused editable.
### Command states

`Command` will have two properties responsible for it's state: (readonly) `isEnabled` and (optional, not always applicable) `isOn`. Those states are independent of themselves, so i.e. a command may be applied and disabled _(this is different from CKE4 where command had "tri-state" so it could be either on, off or disabled)_.

If a command is enabled, it means that it can be executed. Executing command which is not enabled should neither make any changes to Tree Model nor trigger any events. `isEnabled` value might depend on multiple factors:
- a command (or corresponding feature) itself might decide that it is disabled, or
- a command might be disabled because it's schema is invalid with focused editable's schema, or
- a command might be marked by other command or part of code as disabled (other code disables the command).

Because a command might be "locked" by multiple sources, simple `isEnabled` property doesn't cut it. At one moment, a command might be enabled by itself but other commands or plugins might make it disabled anyway. We need a chain of callbacks. If any of those callbacks decides that command should be disabled, it will be disabled no matter what.
_(More clarification on this subject is needed, I remember we were discussing binding events, but forgot details.)_

If a command has `isOn` property, and the property is `true`, it means that it has been executed for given editable / selection. Not every command will have this property, for some it won't make a sense.

It is little ambiguous what is the exact meaning, but this flag changes the behavior or execution method. Before `Command` is executed for the first time, `isOn` should be set to `false`. After command execution, it should change to `true`. Then, next execution should acknowledge that the command is on and apply different execution, to revert back to Tree Model state from before first command execution. Value of this state is completely dependent on `Command`. In other words, it is only a `Command`'s responsibility to introduce algorithm that decides if a `Command` is on. In most scenarios it will  simply depend either on `Selection` attributes or `Selection` position parents.

Command should have methods which will refresh state of `isOn` and `isEnabled` on demand. Making those properties as getters and trying to resolve their value each time they are accessed might be too inefficient.

_(Proposal: change `isOn` to `isApplied` as it is more meaningful name and harder to confuse with `isEnabled`.)_

It was also discussed, that we may introduce a few abstract, base classes for commands which behaves similarly (i.e. `StyleCommand` for commands like `bold`, `italic`, `strike`).

**Comment by fredck** [comment]
> Commands are classes that allow for manipulations on Tree Model.

I don't feel that commands should be **limited** to Tree Model manipulation only. Actually, the concept of commands has nothing to do with the data model. It is actually deviated from features. Therefore commands should be the actions that perform such features.

We may have many commands that don't touch data. For example, `maximize`, `save` or `copy` could be toolbar features that should be execute as easily as any other feature.

We cannot avoid having commands, having just features, because a single feature may introduce more that one command. For example, the `link` feature may introduce the `link` and `link:remove` commands.

The commands concept works well for v4. The only problem I remember we had with it is when executing commands that accept options, like the "font" command. We should figure out a way to support this well, so every user action can be performed in the same way.

As for the `isOn` property, I would call it `isActive`.

**Comment by Reinmar** [comment]
> As for the isOn property, I would call it isActive.

+1 

> I don't feel that commands should be limited to Tree Model manipulation only

+1.

> If there are more commands, use `Feature:command`

Hm... It uses the events convention, but the config convention uses `.`. I wonder whether we're not starting a mess here, having two conventions for namespacing in strings.

> The only problem I remember we had with it is when executing commands that accept options, like the "font" command. We should figure out a way to support this well, so every user action can be performed in the same way.

Yeah... this is a :horse:. We can either create separate commands for each value (but then in case of values like bg colors we'll have too many of them...) or say that commands accept values (but then how to implement different state for each value ;/). It's very tricky. We'd need sth like commands generator... e.g. you would have a generic "bgColor" command, but if you want to check its state, execute it, or do whatever, then you need to provide the context.

I imagine sth like this:

```
editor.commands.add( 'bgColor', ( color ) => {
    return new BGColorCommand( color );
} );

editor.commands.get( 'bgColor', '#123' ) === editor.commands.get( 'bgColor', '#123' )

editor.commands.get( 'bgColor', '#123' ).isActive;
```

**Comment by Reinmar** [comment]
> Command should have methods which will refresh state of isOn and isEnabled on demand. Making those properties as getters and trying to resolve their value each time they are accessed might be too inefficient.

I think that in this case `isOn` and `isEnabled` should work differently.

1. The value of `isOn` should, in general, depend only on the logic of this specific command. Hence, the command will know on what events it should listen so it can simply do that.
2. The value of `isEnabled` is a result of a group of listeners. None of them can with a full certainty say that now the command should be enabled, so rather than changing the state it should `refresh()` the command (or `checkEnabled()`). So, in this case most of these listeners will execute their logic once asked to do so. However, features must still listen to certain events to know when to ask for `checkEnabled()`.
  We can for instance assume that most commands need to check their state on selection change – this can be automated by in one of command classes. For instance, the `AttributeCommand` will check it state on each selection changes, while `FormatCommand` only on block level selection changes (we can have more contextual selection change events for typical situations).

**Comment by Reinmar** [comment]
> `editor.commands.get( 'bgColor', '#123' ) === editor.commands.get( 'bgColor', '#123' )`

Actually, I'm not sure about this. Let's assume that someone implemented color panel in a way that it checks the state for each color that it displays. This means that after such panel was opened, there would be a hundred commands kept in the memory. Perhaps it'd be better if they were not cached. But then we'll have lots of create-destroy logic and... that doesn't seem to be feasible, because developer would need to call `command.stopListening()` manually. Otherwise the pile of listeners would grow because commands would not know when to detach themselves.

**Comment by scofalik** [comment]
+1 fo `.isActive`.

I don't like this "command factory" concept. As we already discussed, `.isActive` is an optional parameter, it won't be defined in base `Command` class. This will be useful for `Command`s that doesn't keep state but only perform an action.

Same goes for commands with non-Boolean state. Why such a command can't have `.state` or similiar property? The downside I can see is that some commands would have to be executed with additional parameter but why really that should be bad? We would have to jump through hoops anyway, no matter what solution we use, and this one seems pretty clean.

If UI will be able to respond to `true`/`false` changes of `.isActive` property, why couldn't it respond to other variable type change?

**Comment by fredck** [comment]
What about replacing `isActive` with `value`?

Then, it'll be up to the command to set the value to something that is useful. At the same time, if the value is not `null` (falsy, actually), it "is active". So a boolean command would simply set it to `true`, while other commands, like font, would simply set the value of the current active font, or one array of active values, or whatever makes sense for the command.

Then, for executing the command, `exec( commandName, [value] )` would probably do the job. Actually, It would be even nicer because it would allow for forcing "bold", for example, to be removed if one wants it, by simply calling `exec( 'bold', false )`.

**Comment by scofalik** [comment]
It's fine by me.

**Comment by Reinmar** [comment]
Makes sense. But of course `value` would still be an optional property (more of a convention in fact).

**Comment by scofalik** [comment]
This is the first draft of `Command`. I will post `AttributeCommand` in #128 .

I don't know if it is a good idea, but this is nowhere near final code and I put it here for discussion.

```javascript
export default class Command {
	/**
	 * Creates a new Command instance.
	 */
	constructor( editor ) {
		this.editor = editor;
		this.isEnabled = true;
		this._selfDisabled = false;
	}

	checkEnabled() {
		if ( this._selfDisabled || !this.checkSchema() ) {
			this.isEnabled = false;
			return;
		}

		this.fire( 'command:checkEnabled' );
	}

	checkSchema() {
		// Should be overwritten in child class.
		return true;
	}

	disable() {
		this._selfDisabled = true;
		this.isEnabled = false;
	}

	enable() {
		this._selfDisabled = false;
		this.checkEnabled();
	}

	execute() {
		// Should be overwritten in child class.
	}
}

utils.mix( Command, EmitterMixin );
```

**Comment by Reinmar** [comment]
I (and @pjasiun) have seen this differently. There should be no `disable()` and `enable()` methods as no one can single-handle decide how long the command should be disabled or enabled. This decision must be a result of asking all listeners for their decision. Even things like schema checks could be one of the listeners (added by default when some method is present in the command).

I see that in CKE5 we don't have the mechanism that `fire()` returns false if one of the listeners cancelled the event, so we need to figure out why we don't have it and if we can't have it, use some other way (object passed to each listener).

So, in CKE4 terms, command would contain:

```js
constructor() {
  if ( this.checkSchema ) {
    this.on( 'checkEnabled', ( evt ) => {
      if ( !this.checkSchema() ) {
        evt.cancel();
      }
    }
  }
}

checkEnabled() {
    this.enabled = !!this.fire( 'checkEnabled' );
}
```

**Comment by scofalik** [comment]
Some explanations:

1) Enabled / disabled

It is true, that no other piece of code should be able to just turn command on or off. However we were discussing that command should be able to turn off itself. Hence I introduced `_selfDisabled` property. It was mistake to make `enable()` and `disable()` public, though, but I created them to easily handle `_selfDisabled`.

At the beginning, I had this `enable()` and `disable()` add / remove `checkEnabled` event. I thought it was overcomplicated, so I did it this way. Maybe it is better idea to have those methods private, and add an event that will turn the command off.

2) `EmitterMixin.fire`

I also noticed, that `.fire` does not return a value. Because of that, I envisioned event callbacks to look something like this:
```javascript
constructor() {
    let otherCommand = this.editor.commands.get( 'other_command' );
    otherCommand.on( 'checkEnabled', function( evt ) {
        // do stuff ...
        if ( disable ) {
            this.isEnabled = false;
            evt.stop();
        }
    } );
}
```
Anonymous function is used because AFAIR arrow function keeps current `this` context and we want that context to change to `otherCommand`. Or we could use arrow function and `otherCommand.isEnabled` instead.

We also have to decide what capabilities those listener have. I think there are 3 logical decisions that listener can take:
* do nothing - do not change command's enabled state, let other decide and if everyone does nothing, command is enabled
* set `isEnabled` to `true` and stop event - the listener is certain that it knows the best and makes the command enabled no matter what
* set `isEnabled` to `false` and stop event - the listener decides that command should be disabled

Whenever we set `isEnabled` state we have to stop event because it will be meaningless otherwise. I think that in 99% of cases we will just use "do nothing" and "set to false", as "set to true" seems weird / dangerous to me (do you have any real case scenarios in CKE4 for this behavior?)

I can also make `EmitterMixin.fire` return a value. Maybe it should return a value returned by last event callback? If event got stopped, it would return last returned value before stop. If all callbacks were called, it would return the value of last callback.

If we had such mechanism, the list above would look like this:
* do nothing - just return `true`
* force enable - stop event and return `true`
* force disable - stop event and return `false`

Also event callbacks would be simpler and look more natural (`Command.checkEnabled` as well).

**Comment by Reinmar** [comment]
> Hence I introduced _selfDisabled property. It was mistake to make enable() and disable() public, though, but I created them to easily handle _selfDisabled.

Yeah, I wanted to write that we could add some helpers for the command itself to handle its state. Those methods/properties would need to be protected and I think that it would be good if they were used like the `checkSchema()` in my example. This way, the `checkEnabled` event will always be used to query the state, no other logic will interfere.

> I also noticed, that .fire does not return a value. Because of that, I envisioned event callbacks to look something like this:

Yeah... we need to decide what we want to do with the emitter. I liked a lot when `fire()` was returning a value because it was super simple then. To say "no" you just had to cancel such event. If anyone wanted to override your decision, a higher-priority listener had to be added. Also, saying a definite "yes" could only be done by stopping the event and returning a value (actually, I'm not sure that CKE4's events actually handled returning a value – we were using `evt.data` for that). I think that this model would work perfectly here as well, so I'd propose extending the emitter.

This will conflict with https://github.com/ckeditor/ckeditor5-core/pull/29, but as we talked some time ago, having events which have a dual nature (are sync or async depending on what the listeners have done) would not be good. I liked the idea of async events, but then all of them would need to be async or we would need to tell what's the nature of the event when firing it. Taken the complexity of this implementation, I'm rather leaning towards rejecting the PR. Perhaps there are better solutions for such pipelines - e.g. stream-like API. If we'll need it, we can think about extending the emitter.

**Comment by scofalik** [comment]
I am for chaning `EmitterMixin.fire`.The change actually is very small and given that both me and you were expecting that `.fire` returns a value I think it will feel natural.

**Comment by fredck** [comment]
This is the reason for `fire()` to not return anything: https://github.com/ckeditor/ckeditor5-core/pull/29. Changing this behavior now will make implementing that feature impossible. Only if it keeps returning a promise with a "cancel" flag.

**Comment by scofalik** [comment]
https://gist.github.com/scofalik/7bbec5ba91ba2138f65b

If fire returned a value, that would be a new implementation.

**Comment by Reinmar** [comment]
While discussing https://github.com/ckeditor/ckeditor5-core/issues/209 with @oleq we realised that in CKEditor 5 there will be no commands like `focusToolbar`, `collapseToolbar` (we had those in CKEditor 4).

The reason why we can't make them commands is that there may be many toolbars. Also, it's clear from one more perspective – there will be no toolbar feature, because what toolbars are used is the creator's decision (no more adding 'toolbar' to `config.plugins`).

All this would be quite obvious when we would work on the code, but it's nice to see the rules.

**Comment by pjasiun** [comment]
> What about replacing isActive with value?

:+1: That's a cool idea. We should not think only about a button as a toolbar item for command, it could be anything (https://github.com/ckeditor/ckeditor5-core/issues/209), and the boolean `isActive` makes sense only for buttons.

> I (and @pjasiun (if we understood each other correctly)) saw this differently...

The original concept was born here: http://dev.ckeditor.com/ticket/12929 and is pretty similar to @scofalik last gist. I only do not like the name of `checkEnabled` method. This is the method which will be called on selection change or editor state change (e.g. readonly) to refresh enability. It is called to refresh not to check. If I turn on readonly I know that the command is disabled, I do not need to check it, I need to refresh its state.

Also, for many cases, all commands will need to be refreshed at once (readonly, nested editable). I am not sure if each command should have a separate event.

> Whenever we set isEnabled state we have to stop event because it will be meaningless otherwise. I think that in 99% of cases we will just use "do nothing" and "set to false", as "set to true" seems weird / dangerous to me (do you have any real case scenarios in CKE4 for this behavior?)

I totally agree. Each listener can said if the command is disabled, but none will be sure that it is enabled.

**Comment by Reinmar** [comment]
https://github.com/ckeditor/ckeditor5-core/compare/t/features?expand=1#diff-2ce4a9c4c2c2bf320df2efab7881c510R43 - it's a super minor thing, but every time you need to add a listener, think whether you couldn't reuse the existing one (the one registered in the constructor). Less memory, faster execution. In this case you could store the information whether disable() was called in a private property and check it in the existing constructor.

**Comment by pjasiun** [comment]
https://github.com/ckeditor/ckeditor5-core/compare/t/features?expand=1#diff-f773ec75a68e511125655a5e6f348c68R33 This code is not needed. The generic case (walker) should handle collapsed range fine enough.

**Comment by scofalik** [comment]
Either I am having brain malfunction or you are not right. First of all you have to note that for collapsed selection, we force item name `inline` (text). This is how query looks like if we put it together:
```javascript
const query = {
	name: !step.value || !step.value.item.name ? 'inline' : step.value.item.name,
	attribute: this.attributeKey
};
```
This is fine.
But.

I can't simply leave it as it is with:
```javascript
let item = step.next();
while ( !step.done ) { ... }
```
Because the code inside loop (so the schema check) will never fire for collapsed selection.

I also can't do
```javascript
do {
  item = step.next();
  ...
} while( !step.done );
```
This will fire for collapsed selection, but it will also fire an extra step for non-collapsed selection, so it will result in checking all nodes in selection + a position after selection like it was a collapsed selection. This incorrectly returns `true` if there is one element selected that can't have the attribute applied (it should return `false`).

**Comment by pjasiun** [comment]
Right. It makes sense that for the range you check if this content, which **already is there**, can be bolded and for the collapsed range you check if the text can be **inserted** there.

**Comment by Reinmar** [comment]
This part of architecture turned to not be something concrete. Features are implemented in many ways, usually in forms of plugins, and use a wide range of APIs. This will be covered in the docs of course.
