### ISSUE TITLE
Naming guidelines in code

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#16]
Other than standard naming convention syntax, there are guidelines that should be followed when deciding for names.
- [x] 1. Underscore on private properties/methods.<br>
  E.g. `CKE._counter`, `something._doInternalTask()`.
- [x] 2. Methods/Functions are **almost always** verbs/actions.<br>
  Good: `execute()`, `this.getNextNumber()`.<br>
  Bad: `this.editable()`, `this.status()` (get when empty / set when with parameter)
- [x] 2.1. The exception for the above are get/set methods, that are used very often, where the first parameter is the thing to get/set and the second is the optional value (set with it and get without).<br>
  E.g: `this.data()`, `this.attr()`.
- [x] 3. Properties/Variables are **almost always** nouns.<br>
  E.g.: `this.name`, `this.editable`, `editor`.
- [x] 3.1 Boolean properties are **always** prefixed by an auxiliary verb.<br>
  E.g: `this.isDirty`, `this.hasChildren`, `this.canObserve`, `this.mustRefresh`.
- ~~4. Properties/Variables names as adjectives **are not prefixed** with "is".
  <br>Good: `this.dirty`, `this.ready`.
  <br>Bad: `this.isDirty`, `this.isReady`.~~
- [x] 5. Properties that require computation **can** use getters/setters and are named as nouns instead of implementing them as getXXX() and setXXX() methods when they are programmatically and conceptually simple.<br>
  Good: `this.status`, `editor.setEditable(); editor.editable /* readonly */;`.<br>
  Bad: `this.getStatus(); this.setStatus( 1 );`, `editor.editable = x /* setter */;`
- [x] 6. Commonly acceptable short versions for long names are fine:
  <br>E.g.: `attrs`, `doc`, `el`.

**Comment by Reinmar** [comment]
Turns out we weren't very found from the previous list of short names because we violated it many times, so it's time to clean this up. I can see that we were naturally shifting towards using full names in public API, so here I reflected this change:

https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style-Naming-Guidelines/_compare/9f3699a0d74a4cf5ef439536440b94b89b2b6caa...c7de1c89e5c079f33eb8b77458ae1216adc011bf

Current version: https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style-Naming-Guidelines#shortcuts

"el" and "attr" are only allowed in private variables, but not in method, property etc. names.
