### ISSUE TITLE
CKEditor not working with Semantic-UI modal

### ISSUE THREAD

**Issue by hoa-ho** [ckeditor/ckeditor5-design#164]
I've been using Semantic-UI components on my website; however, I'm trying to implement CKEditor into Semantic-UI popup modal, but it is not working. I can't type into the text area. When I click the default styling buttons in the textarea, it gives me this error: **Uncaught TypeError: Cannot read property 'getSelection' of undefined.** 

If I implement the CKEditor into a regular div element, it will work though. But I need it to work inside a pop up modal. Can somebody help me? Thanks!

**Comment by Reinmar** [comment]
Sorry for your trouble. However, this is CKEditor 5's issue tracker and I'm pretty sure you use CKEditor 4. Am I right?

If so, you should report the issue in this issue tracker: http://dev.ckeditor.com. You'll have to provide more details, though, preferably a working sample. Otherwise, there's little chance anyone will be able to help you.

I'm closing this ticket. But if it'll turn out that you're using CKEditor 5, we can reopen it.
