### ISSUE TITLE
Documentation: Data Processing

### ISSUE THREAD

**Issue by chihab** [ckeditor/ckeditor5-design#183]
Is the Data Processing workflow here [https://github.com/ckeditor/ckeditor5-design/wiki/Data-Processing](url) up to date with the current version ?

Is it possible to have some data samples on each step of the workflow ?

Something like:

- Load  "Data" from Db:  
```xml
 <chapter>
   <title>Data Processing</title>
   <content>Data Processor converts this XML to Dom Document</content>
 </chapter>
```
- Custom Data Processor converts to Dom Document (JSON Representation):
 ```js
{
    "_children": [
        {
            "name": "h2",
            "_attrs": {},
            "_children": [
                {
                    "_data": "Data Processing"
                }
            ],
            "_classes": {},
            "_styles": {},
            "_customProperties": {}
        },
        {
            "name": "p",
            "_attrs": {},
            "_children": [
                {
                    "_data": "Data Processor converts this XML to Dom Document"
                }
            ],
            "_classes": {},
            "_styles": {},
            "_customProperties": {}
        }
    ]
}
```

- Create the Data Model
...

**Comment by scofalik** [comment]
Hello!

The article is actually quite up-to-date. Your samples are also pretty accurate.

1. As explained, the data that you save/load from a database can be of any format, but usually, it is HTML.

```html
<h2>Header</h2>
<p>Some <strong>text</strong> in paragraph</p>
<ul>
  <li>List item 1</li>
  <li>List item 2</li>
</ul>
```

2. Then, the data is converted to DOM and then from DOM to the editor's view structure. The view is like a kind of a virtual DOM - our custom representation of DOM. The JSON that you have pasted looks like stringified `view.DocumentFragment`. Internally, we'd rather write it down in like HTML, and in fact, it is the same:

```html
<h2>Header</h2>
<p>Some <strong>text</strong> in paragraph</p>
<ul>
  <li>List item 1</li>
  <li>List item 2</li>
</ul>
```

3. Then, the view is converted to the model, using converters, that were registered by features. Each view element is analyzed and converted to the model which is the editor's data structure. Once again, it is easier to use "html-like" notation instead of JSON string.

```html
<heading1>Header</heading1>
<paragraph>Some <$text bold="true">text</$text> in paragraph</paragraph>
<listItem indent="0" type="bulleted">List item 1</listItem>
<listItem indent="0" type="bulleted">List item 2</listItem>
```

Note, that inline elements like `<strong>` or `<em>` are stored in model as attributes set on `model.Text` nodes. We differentiate texts with and without attributes by using `<$text>` "tag".

4. When the data is saved to a database (`editor.getData()` is called) it's all the same but backward. Model is converted to view, view is converted to DOM, DOM is converted to HTML. Then you get the output HTML as a result of `editor.getData()` and you may save it in your DB.

I hope that clarified things a bit.

**Comment by Reinmar** [comment]
Data processor and the whole concept needs to be indeed documented on docs.ckeditor.com.

**Comment by Reinmar** [comment]
I reported a ticket for it in https://github.com/ckeditor/ckeditor5/issues/708. We're slowly closing the ckeditor5-design repo so it's better to track it there.

**Comment by chihab** [comment]
Thanks a lot @scofalik. It has clarified a lot.
Okay @Reinmar, if I have more questions I'll post them on the issue you've referenced.
