### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#25]
The API and guides documentation solution we'll adopt in CKEditor 5 must be discussed and implemented.

**Comment by mlewand** [comment]
In fact **[JSDoc](https://github.com/jsdoc3/jsdoc/blob/master/README.md)** is an interesting option, which is I guess the most known annotation standard out there.

JSDuck is now pretty much [dead and burried](https://github.com/senchalabs/jsduck/graphs/contributors) for quite some time as opposed to JSDoc which keeps [sustainable, healthy](https://github.com/jsdoc3/jsdoc/graphs/contributors) status.

JSDuck has some problems:
- it's written in yet another language (ruby) and comes with a big dependency (most painful is sencha sdk, that tends to be [unavailable for weeks](http://www.sencha.com/products/sdk-tools/download/))
- it's not popular, therefore some of IDE are missing support for it (hate to see `@memberOf` rather than `@member` in my code complete :( )
- poor markup in the output (eg. in API tree some links are div with click listeners)

The downside is ofc that we would need to make a beautiful styling for new docs rather than using the default one.

If we're looking for adding features, it looks like JSDoc is even pretty extensible allowing us to add whatever we like.

Since CKEditor will be rewritten for the most part, it's a good moment to improve our annotations.

**Comment by Reinmar** [comment]
> (most painful is sencha sdk, that tends to be unavailable for weeks)

? WFM.

> JSDuck is now pretty much dead and burried for quite some time as opposed to JSDoc which keeps sustainable, healthy status.

3 years ago JSDuck also was super healthy and it reached a level of feature-completeness which makes it very useful and powerful. Most likely it's also a reason why the development slowed so much. Not every tool in the world needs to be continuously changed. BTW. Note that most of the issues have replies from the maintainer - https://github.com/senchalabs/jsduck/issues.

Anyway, if we want to consider JSDoc, we need:

* either find examples of rich and cute JSDoc implementations for **big** docs (note - we'll have hundreds classes again),
* or dig deep into JSDoc to learn what's possible.

**Comment by Reinmar** [comment]
> > (most painful is sencha sdk, that tends to be unavailable for weeks)
>
> ? WFM.

Aaaand it doesn't work for me any more. Moreover, I checked the whole picture more closely and it doesn't look that well. Sencha apparently doesn't maintain old stuff well - I couldn't find anything about Sencha SDK tools, including any information about changelog, previous versions. Pretty much nothing.

Therefore, I would, as Marek proposed, consider JSDoc. However, it seems that we'll need to build something more rich around it, so it's not all roses too.

**Comment by gregpabian** [comment]
I'm for JSDoc3 as well (been using it for years), though it will require some amount of work to make the output good looking and easy to use. Anyway, +1 here.

**Comment by Reinmar** [comment]
I've spent few minutes googling and I haven't found a single good looking theme :D. Another thing is what I mentioned earlier - our docs are huge comparing to the examples I can find. So not only we'll need proper theme, but entire UI. This will be a pretty big project itself :D.

**Comment by fredck** [comment]
Hum... things got more complicated now, since we decided to go ahead with ES6.

I've found this so far: https://esdoc.org/

**Comment by Reinmar** [comment]
I've just stumbled upon http://documentation.js.org/

**Comment by Reinmar** [comment]
After performing review existing tools we chose JSDoc for which we're preparing our own theme. That said... JSDoc is buggy and not well maintained but at the time it looked best anyway.
