### ISSUE TITLE
API docs code style

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-design#27]
One more thing we haven't yet mentioned is API docs code style. There's a [pretty detailed guide for CKE4](http://docs.ckeditor.com/#!/guide/dev_code_documentation) and we will need one for CKE5 too. I propose simply accepting the same rules, but updating cases to match examples from CKE5.

I also [updated the Code Style wiki page](https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style/_compare/0be56a3d9f11dc78a3582566b0a42890a27e48db...59968454953d5ad54e186d60afd06ee1fd59507c) to match these rules.

I would also like to write few JSCS rules (JSCS is pluggable) which will verify the most common mistakes like orders of tags or missing new lines. I don't think though, that we can run JSDuck to validate correctness of the docs like we'll run JSCS ans JSHint tasks.

**Comment by mlewand** [comment]
Do we want to stick to JSDuck for our next-gen CKEditor? We may check for a best doc option out there.

Interesting option is **[JSDoc](https://github.com/jsdoc3/jsdoc/blob/master/README.md)**, which is I guess the most known annotation standard out there.

JSDuck is now pretty much [dead and burried](https://github.com/senchalabs/jsduck/graphs/contributors) for quite some time as opposed to JSDoc which keeps [sustainable, healthy](https://github.com/jsdoc3/jsdoc/graphs/contributors) status.

JSDuck has some problems:
- it's written in yet another language (ruby) and comes with a big dependency (most painful is sencha sdk, that tends to be [unavailable for weeks](http://www.sencha.com/products/sdk-tools/download/))
- it's not popular, therefore some of IDE are missing support for it (hate to see `@memberOf` rather than `@member` in my code complete :( )
- poor markup in the output (eg. in API tree some links are div with click listeners)

The downside is ofc that we would need to make a beautiful styling for new docs rather than using the default one.

If we're looking for adding features, it looks like JSDoc is even pretty extensible allowing us to add whatever we like.

Since CKEditor will be rewritten for the most part, it's a good moment to improve our annotations.

So what about that? Are we attached to JSDuck `for good and for worse` or can we consider using other annotation system/doc generation tool?

**Comment by Reinmar** [comment]
Didn't we have somewhere a dedicated thread for this topic? I remember we started the discussion, but I can't find it.

**Comment by mlewand** [comment]
Yea, there's a similiar issue #25. So i'll move the post to the second issue, as this one should be about the doc style - despite of what doc api is used.

**Comment by Reinmar** [comment]
I guess we'll port the old docs to CKE5 docs at some point. We didn't change the code style for API docs.
