### ISSUE TITLE
Toolbar design

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-design#49]
The v4's toolbar has some nice features like groups and ability to move the toolbar around (top space, bottom space, shared spaces), but it lacks features related to buttons organisation (grouping, hiding, tabs, etc.). Some very good points can be found in http://dev.ckeditor.com/ticket/12803

(We're not starting designing the UI yet, but I didn't want to lose that ticket).

**Comment by AnnaTomanek** [comment]
A side note: let's not forget about the Artur's Toolbar Configurator when thinking about the toolbar design.

**Comment by Bojhan** [comment]
Please let me know when you are starting work on this.

**Comment by wimleers** [comment]
And please ping @tkoleary too.

**Comment by SteveTheTechie** [comment]
Another thought I had on this was that since CKEditor already has the option to collapse the toolbar, perhaps there could be an option that collapsing the toolbar could instead show a horizontal bar menu on the currently empty grey bar (via a plugin).  This way, the users that like icons can have icons and users that like menus could have a menu, and the collapse button could just serve to switch between the two.

**Comment by Reinmar** [comment]
Cleaning up outdated discussions. See https://github.com/ckeditor/ckeditor5-design/issues/186
