### ISSUE TITLE
Name convention for mixins

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-design#52]
I would like to propose mixins to be named with the following scheme:

```
( UpperCamelCase noun ) + 'Mixin'
```

E.g. `EmitterMixin`.

It would be similar to classes, postfixed with 'Mixin'.

**Comment by Reinmar** [comment]
The current `EmitterMixin` is just an object with additional methods, so currently we extend some class's prototype with it. If we decide that some mixin should also add static method, then a useful thing will be to have a method which adds static and prototype's methods. E.g.:

```
Emitter.mixin( Model );
```

Note that you already created the `Emitter` module in CKE5 but now it returns `EmitterMixin`. I think that the former is nicer - return an `Emitter` which has a static `mixin()` method which does the job.

**Comment by Reinmar** [comment]
PS. This is how we do it in CKE4. The `Event` class has a static `implementOn()` method.

**Comment by adelura** [comment]
I would avoid adding static functions to mixin. Do we need this really? Static function should be added to specific constructor of util object. And there is another topic "inheriting static functions" I would avoid this.

----

Please note that mixin doesn't only have functions but properties as well. I think we should define them as well i the same way how we define functions in mixin. Then we are on a good way to implement some mechanism which will catch properties collision.

----

How about intoduce constructor Mixin and force all mixins inherit from main Mixin class, and make all sepcific mixin like `EmmiterMixin` to be a Constructor as well. This will allow us to implement method like `isImplementing` which will give us information whether concrete instance implement some mixin.

``` js
function doStuff( something ) {
    var isEmmiter = something.isImplementing( EmmiterMixin ); // true

    // do stuff

    if ( isEmmiter ) {
        something.fire( 'stuffDone' );
    }
}
```
This could also allow us to operate on objects more like on interfaces.

**Comment by fredck** [comment]
> How about intoduce constructor Mixin and force all mixins inherit from main Mixin class, and make all sepcific mixin like EmmiterMixin to be a Constructor as well. This will allow us to implement method like isImplementing which will give us information whether concrete instance implement some mixin.

Let's not mix things here... mixins are simply made by objects that hold a set of properties which are copied to a target. By definition, there is no class inheritance on this (which drops the `isImplementing()` idea).

Currently we do this in a very simple way:

```js
utils.extend( target, mixin );
```

So let's assume that the API is already very simple.

I liked @Reinmar's proposal to make this more explicit though. We could have something like this:

```js
var EmitterMixin = new Mixin( {
    method1: ...,
    method2: ...
} );

function TargetClass() {}

EmitterMixin.mixin( TargetClass.prototype );
```

I would not go crazy on mixin statics and prototype stuff at the same time. This could be confusing and limited (like a mixin that is good as a static as well as a prototype addition). Like the above example, I would just clearly and explicitly point where to mix things in.

I would just insist for the postfixed naming convention. That's because it would be unclear that `Emitter` is not a class... and mixins **are not classes**.

> Note that you already created the Emitter module in CKE5 but now it returns EmitterMixin.

My mistake in fact... the module should be named EmitterMixin as well.

**Comment by mlewand** [comment]
## Naming

I like the idea for adding the `Mixin` postfix. :+1: 

## Mixin Implementation Method

```javascript
Emitter.mixin( Model );
```

@Reinmar's mixin proposition sound good. Proposed name is better than current `implementOn`.  :+1: 

@fredck I belive that placing a prototype rather than a type constructor was just a typo in the following listing:

```javascript
EmitterMixin.mixin( TargetClass.prototype );
```

What we need is simply a type constructor to keep it as simple as possible. The `mixin` method will access the proptotype on its own - but it's an implementation detail that developer does not need to know about.

## the isImplementing method

For me mixin is a way to emulate multiple inheritance (though it's complex, it's extremely handy in particular cases). Because of that, on paper, @adelura method sounds like a valid use because in OOP langugages with multiple inheritance you can "discover" if instance/class implements given interface.

But looking at the problem from practical point of view, I can't recall a single case that I needed to ensure that my client object implements given interface.

Working with CKEditor I **always** knew that my client implements event mixin (period).

Maybe that was due to our GIGO rule...

## Static Methods/Props Implementation

KISS. Proposed interface will be capable of doing that if there will be a need to. But since we don't really use it for the time being I suggest to skip it now coz YAGNI.

**Comment by fredck** [comment]
> @fredck I belive that placing a prototype rather than a type constructor was just a typo in the following listing:
> 
> EmitterMixin.mixin( TargetClass.prototype );

> What we need is simply a type constructor to keep it as simple as possible. The mixin method will access the proptotype on its own - but it's an implementation detail that developer does not need to know about.

No, it wasn't a typo... it's was on purpose.

My point is that mixins can be used to extend classes prototypes, but also constructor functions, object, etc. So I wanted to make it more explicit.

I mean... it is whatever that extends whatever... not a class that extends a class.

**Comment by Reinmar** [comment]
> My point is that mixins can be used to extend classes prototypes, but also constructor functions, object, etc. So I wanted to make it more explicit.

Hmm... good point. It is user's decision where this mixin should be injected.

**Comment by fredck** [comment]
In fact, all this would be very similar to what we have now:

```
utils.extend( TargetClass.prototype, EmitterMixin );
```

... it would be just more explicit (and beautiful to see :)).

**Comment by fredck** [comment]
Updated the [documentation for naming conventions](https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style#naming) and opened two tickets for this:
https://github.com/ckeditor/ckeditor5-core/issues/17
https://github.com/ckeditor/ckeditor5-core/issues/18
