### ISSUE TITLE
Merge commit message.

### ISSUE THREAD

**Issue by adelura** [ckeditor/ckeditor5-design#55]
Current merge branch approach is as follow:

We run command `git merge --no-ff t/1337`. It creates a merge commit message `Merge branch 't/1337'`. Since in v5 and other related projects we moved entirely to github it would be nice to reference merge commit with related issue on github issue tracker.

I suggest to drop default commit message and use custom one which include "fix #1337" or "fixed #1337".

Something like "Merge branch 't/1337'. Fixed #1337.". It will automatically reference merge commit issue, so if someone come back after a while they will have instant access to changes made during issue development.

We can achieve this by using `-m` flag during merge.

**Comment by Reinmar** [comment]
In CKEditor 5 repos we merge branches by accepting PRs, so the messages look like this: https://github.com/ckeditor/ckeditor5-core/commit/acd72a00101edb4d0d5f90dd098e374ed09cd12a - "Merge pull request #19 from cksource/t/16". You have the PR referenced and PR refers to an issue number. Should be enough.

**Comment by adelura** [comment]
Cool, how about related projects?

**Comment by Reinmar** [comment]
In some repositories we do not make PRs indeed and you're right that adding an issue number makes opening the issue page faster. But since the branch name contains an issue number you can find the issue anyway - it just takes few seconds more. So I don't think that we must add "Fixed #xxx." to the merge commit. We can do this though. Especially if it closes the ticket automatically and creates a reference from the ticket to the merge commit - that would save few seconds more and would actually be really helpful :).

**Comment by adelura** [comment]
To quickly find merge commit you have to use some git gui and have to have **cloned repository** on your disc. I don't see such functionality on github to find commit by message. Btw. I don't use any gui (instead of one which is built in my webstorm).

**Comment by Reinmar** [comment]
See https://github.com/ckeditor/ckeditor5-design/issues/30
