### ISSUE TITLE
Plugins, libraries and creators 

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-design#60]
Working on CKEditor4 I met a problem that what I was sometimes creating was not in fact a plugin, but more a tool, set of functions, helpers, library. Such module does not need to have to be initialized, because it does not depends on the editor instance. The example of such library may be `lineutils` or `filetools`.

We will move also `creators` to the separate modules in CKEditor 5. But these also does not need to be `init` in the way plugins do. They need to be prepared and registered, they may need to have some common interface later too (e.g. to check if the DOM element match to this creator).

Because of above I believe that current `plugins` should be split into multiple classes. 

First of all, there should be multiple base classes, one for each type. But there is more. Creators should be registered in the CKEDITOR scope automatically and libs does not need to have the init function, so they does not need to to save it's dependencies (`requirejs` will handle them). Therefore they should be called differently:
 - `ckeditor5-plugin-image` - feature, needs an `init( editor )` function,
 - `ckeditor5-lib-image` - works on the `CKEDITOR` scope, does not have an `init` function,
 - `ckeditor5-creator-classic` - is registered and can be used to create an editor instance.

When user create an instance of the editor he needs to define only what plugins he wants to use, so we will have no naming collision.

**Comment by fredck** [comment]
-1

We don't need this kind of complication in the API. A simpler approach could be found.

Plugins are named like this because they're loaded on demand based on (1) configurations and (2) cross-plugin dependencies.

It is true that many plugins will also have this kind of tool/library use (lineutils was a good example). So the only think I would do here would be making `init()` optional on the plugin definition or even make it optional for the plugin to return an instanceof `Plugin`.

Creator is a bad example because it is not a tool. In any case, we've discussed the same thing in another thread:
https://github.com/ckeditor/ckeditor5-core/pull/27#discussion_r32502480

**Comment by Reinmar** [comment]
Just stumbled upon this and turns out that during one of F2F discussions with Fred we decided that having a naming convention for plugins exposing creators (and perhaps some other modules) would be great because it would allow us to not have a completely useless collection of creators in every editor instance.

I'll get back to Fred's PR soon and straighten these things up.

**Comment by Reinmar** [comment]
I can see that Fred already mentioned that in https://github.com/ckeditor/ckeditor5-core/pull/27#issuecomment-123594951

**Comment by Reinmar** [comment]
I will open a new issue to not mix too many thread together.

Resolution for this issue is as follows – creators will be special kind of plugins and perhaps the UI libraries too (research in progress). Creators most likely will inherit from the `Creator` class which will extend the the `Plugin` class. We can use this or similar approach for other kinds of plugins, but at this moment we don't see other needs. All plugin names (including creators and UI) will need to start with `ckeditor5-plugin-*`. The prefix can be followed by `creator-*` or `ui-*`.
