### ISSUE TITLE
The project name

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-design#78]
We automatically started using the name CKEditor 5, because it somehow makes sense that after CKEditor 4 comes CKEditor 5, but the name is the first thing many people see, so it's an important factor.

Looking back at the history we can see that FCKeditor 2 became CKEditor 3 (which has been a total rewrite) and then CKEditor 3 became CKEditor 4 (which was only heavily refactored). To match that "scheme" we would need Keditor 5 :D.

CKEditor 5 will be a full rewrite, so the name could underline that. I think that in the code, repos and versioning scheme we can simply use the number 5 (https://www.youtube.com/watch?v=EK_LN3XEcnw), but for communication and marketing purposes I would propose a different name. For example: ​**CKEditor Mambo**​ or CKEditor Next.

**Comment by scofalik** [comment]
I will just re-post my opinion here:

I had an idea that CKEditor 5 should not be named "5". PJ told me that you were already discussing it and the conclusion was that CKEditor is a brand and you can't change it.

I agree, but it does not have to mean that we need to follow with number 5. The next number implies that the new version inherits more or less from the previous one. Of course not everything will have to be compatible but there is a feeling that there should be visible and functional similarities in each of them.

The truth is that both of those editors will be completly different: code is re-written from scratch, architecture is completly changed, UI will be new, ways how 3rd party developers will write their plugins/features is different. There is no way to "port" plugins or old code, you have to write it once again. It's like changing from horse to a car and asking if your old saddle will fit in your new car.

The reality is that the only things that we want to take from CKE4 is: brand, quality and experience.

I think that CKE5 could (and should) be re-named so it will be connected with CKE but not with CKE4. People can't expect smooth transition into a revamped and tweaked CKE4.

I don't have any good idea now but I am thinking of something like CKEditor X or even CKEditor Zero as we start from the ground (zero-level). Or CKeditor Ultimate. You know. A catchy word that won't be connected by version number to the old software.

**Comment by Reinmar** [comment]
PS. If we're not for changing the name, then perhaps we can at least pick a code name :D.

**Comment by pjasiun** [comment]
I like this Idea very much. It show very well what this project really is: a new project, but still being a "CKEditor". Not an improved version of CKEditor 4 (like 3 -> 4).

What we stress with this name is that:
 - this is a new project, it have new concepts, new ideas, new code; because we are thinking about the CKEditor 5 it the very different way we were thinking about CKEditor 4 we should stress it;
 - this is not the next version of the CKEditor 4, so it will not be possible to port plugins, they will need to be rewritten, you can not expect simply porting;
 - CKEditor 4 is not the old, unsupported version; no matter how hard we will stress this, many people will feel that they need to port to the new version since the old is deprecated; then they will expect all features to be ported, old browsers support and they will be surprised they do not get it.

Also I like the name CKEditor Mambo very much. "Mambo" is short, positive, have 5 letters and I can not find any well known JavaScript project called that way.

The only disadvantage I can fine is that for some people it will be unclear what is "CKEditor Mambo". Is it a separate project, a new version, or what? But that's ok, because it is in fact something in between :)

**Comment by wimleers** [comment]
I prose `LlamaEditor`! :)

Joking aside, I think there are two key considerations that AFAICT are almost polar opposites:

1. CKEditor is well known, so keeping the name will help with recognition.
2. For the same reason, it may also remind people of long past times where CKEditor was very different, unfortunately some people associate it with "shitty HTML".

I don't know which one is stronger. I honestly suspect the first.

That is my outsider POV :)

**Comment by fredck** [comment]
Sincerely, I don't see any chance for the project to have a new name. Building a market around a brand is extremely complex. Not benefiting from the huge market share we have would be also a mistake.

Additionally, the whole problem about the strong differences on the versions is temporary. It can be solved with proper communication instead. It will be irrelevant once CKEditor 5 becomes popular.

**Comment by wwalc** [comment]
Just to support Fred's point of view (and mine), VW Passat:

![800px-vw_passat_b1_v_sst](https://cloud.githubusercontent.com/assets/545175/12486409/f460c878-c062-11e5-9815-1a8c6855a423.jpg)
![vw_passat_b7_2 0_tdi_dsg_highline_kaschmirbraun](https://cloud.githubusercontent.com/assets/545175/12486416/f7190878-c062-11e5-9a76-c9fa568b0038.JPG)

I bet these are two different cars yet they have the same name ;)

**Comment by Reinmar** [comment]
OK, I think that it's clear that we don't want to change the official name. Also, there's not much a need for a code name either.
